#Maintainer : Thibaud LE GALL
#legallthib@wanadoo.fr

FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update \
	&& apt-get install -yq --no-install-recommends \
	apt-transport-https \
	apt-utils \
	build-essential \
	curl \
	g++ \
	git \
	gnupg \
	openjdk-11-jdk \
	protobuf-compiler \
	pkg-config \
	libprotoc-dev \
	software-properties-common \
	unzip \
	vim \
	wget \
	zip \
	zlib1g-dev \
	&& \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*


# Install python 3.8


#RUN add-apt-repository ppa:jonathonf/python-3.8
#RUN apt-get update

RUN apt-get update && apt-get install -y python3-dev python3-pip python3-venv

# Making python3 and pip3 the default commands
#RUN ln -s /usr/bin/python3.8 /usr/bin/python && \
#	python3.8 -m pip install --upgrade --force pip

RUN pip install onnx

RUN mkdir /usr/src/app/ && \
	cd /usr/src/app/
WORKDIR /usr/src/app/

RUN pip3 install torch==1.9.0+cpu torchvision==0.10.0+cpu torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

COPY requirements.txt /home/app/requirements.txt

# Installing the dependencies
RUN pip3 --no-cache-dir install --ignore-installed --upgrade ipython && \
	pip3 install --upgrade pip && \
	pip3 --no-cache-dir install -r /home/app/requirements.txt \
		&& \
	python3 -m ipykernel.kernelspec
	
#import torch
#model = torch.load('data/model/run-1/run-1/models/final.pth', map_location ='cpu')